# Generated by Django 5.2.7 on 2025-11-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('track_id', models.CharField(help_text='Song unique ID (chave primária da busca)', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('track_name', models.CharField(max_length=255)),
                ('track_artist', models.CharField(max_length=255)),
                ('duration_ms', models.IntegerField()),
                ('track_popularity', models.IntegerField(help_text='Song Popularity (0-100)')),
                ('playlist_genre', models.CharField(max_length=50)),
                ('danceability', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Músicas',
            },
        ),
    ]
