# Generated by Django 5.2.7 on 2025-11-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteProcura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='duration_ms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
